name: flirt
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  nuxify_widgetbook:
    git:
      url: git@github.com:Nuxify/widgetbook.git
      ref: release/1.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  lint: ^2.3.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
